"""initial

Revision ID: 53423367c2eb
Revises:
Create Date: 2026-06-22 16:02:44.031955

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "53423367c2eb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


upload_status_enum = postgresql.ENUM(
    "PENDING", "PROCESSING", "COMPLETED", "FAILED",
    name="uploadstatus",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    upload_status_enum.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("track_metadata",
    sa.Column("upload_id", sa.UUID(), nullable=False),
    sa.Column("title", sa.String(), nullable=True),
    sa.Column("artist", sa.String(), nullable=True),
    sa.Column("album", sa.String(), nullable=True),
    sa.Column("albumartist", sa.String(), nullable=True),
    sa.Column("genre", sa.String(), nullable=True),
    sa.Column("year", sa.String(), nullable=True),
    sa.Column("track_number", sa.Integer(), nullable=True),
    sa.Column("disc", sa.Integer(), nullable=True),
    sa.Column("duration", sa.Float(), nullable=True),
    sa.Column("bitrate", sa.Float(), nullable=True),
    sa.Column("samplerate", sa.Integer(), nullable=True),
    sa.Column("channels", sa.Integer(), nullable=True),
    sa.Column("comment", sa.String(), nullable=True),
    sa.Column("cover_key", sa.String(), nullable=True),
    sa.Column("processing_status", upload_status_enum, nullable=False),
    sa.Column("error", sa.String(), nullable=True),
    sa.Column("filename", sa.String(), nullable=False),
    sa.Column("content_type", sa.String(), nullable=False),
    sa.Column("origin_upload_status", upload_status_enum, nullable=False),
    sa.Column("size", sa.Integer(), nullable=False),
    sa.Column("created_by", sa.UUID(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("upload_id")
    )
    op.create_index(op.f("ix_track_metadata_created_at"), "track_metadata", ["created_at"], unique=False)
    op.create_index(op.f("ix_track_metadata_processing_status"), "track_metadata", ["processing_status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_track_metadata_processing_status"), table_name="track_metadata")
    op.drop_index(op.f("ix_track_metadata_created_at"), table_name="track_metadata")
    op.drop_table("track_metadata")

    bind = op.get_bind()
    upload_status_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
