"""empty message

Revision ID: 76729e0db655
Revises: 71d50d3bff25
Create Date: 2026-07-11 17:58:35.225371

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76729e0db655"
down_revision: Union[str, Sequence[str], None] = "71d50d3bff25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_outbox_messages_unpublished_id", "outbox_messages", ["id"], unique=False, postgresql_where=sa.text("published_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_messages_unpublished_id", table_name="outbox_messages", postgresql_where=sa.text("published_at IS NULL"))
    # ### end Alembic commands ###
