"""outbox

Revision ID: 71d50d3bff25
Revises: 53423367c2eb
Create Date: 2026-06-23 13:38:51.586314

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71d50d3bff25"
down_revision: Union[str, Sequence[str], None] = "53423367c2eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("outbox_messages",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("aggregate_type", sa.String(), nullable=False),
    sa.Column("aggregate_id", sa.UUID(), nullable=False),
    sa.Column("event_type", sa.String(), nullable=False),
    sa.Column("payload", sa.JSON(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbox_messages")
    # ### end Alembic commands ###
