services:
  metadata-backend:
    container_name: tempo.metadata.backend
    build:
      context: .
      target: backend
      network: host
    env_file:
      - .dev/docker.env
    networks:
      - local-network
    ports:
      - 8083:8080

  metadata-consumer:
    container_name: tempo.metadata.consumer
    build:
      context: .
      target: consumer
      network: host
    env_file:
      - .dev/docker.env
    networks:
      - local-network

  metadata-publisher:
    container_name: tempo.metadata.publisher
    build:
      context: .
      target: publisher
      network: host
    env_file:
      - .dev/docker.env
    networks:
      - local-network

networks:
  local-network:
    name: local.network
    external: true
