FROM python:3.14-slim AS base

RUN pip install uv==0.11.2

ENV PATH="/app/.venv/bin:${PATH}"

WORKDIR /app
COPY ./pyproject.toml.local-docker /app/pyproject.toml
COPY ./src /app
COPY alembic.ini /app/


RUN uv lock && uv sync --frozen --group local_pypi

# RUN alembic upgrade head -c

FROM base AS backend

ENTRYPOINT python -m app.main.start
# ENTRYPOINT tail /dev/null -f

FROM base AS consumer

ENTRYPOINT python -m app.main.consumer

FROM base AS publisher

ENTRYPOINT python -m app.main.relay
