services:
  management-backend:
    container_name: tempo.management.backend
    build:
      context: .
      target: backend
      network: host
    env_file:
      - .dev/.env.docker.local

    networks:
      - local-network
    ports:
      - 8001:8080

  management-consumer:
    container_name: tempo.management.consumer
    build:
      context: .
      target: consumer
      network: host
    env_file:
      - .dev/.env.docker.local

    networks:
      - local-network

  management-publisher:
    container_name: tempo.management.publisher
    build:
      context: .
      target: publisher
      network: host
    env_file:
      - .dev/.env.docker.local

    networks:
      - local-network

networks:
  local-network:
    name: local.network
    external: true
