"""initital migration

Revision ID: 677671993e85
Revises: 
Create Date: 2026-09-01 17:30:45.442403

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "677671993e85"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("outbox_messages",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("aggregate_type", sa.String(), nullable=False),
    sa.Column("aggregate_id", sa.UUID(), nullable=False),
    sa.Column("event_type", sa.String(), nullable=False),
    sa.Column("payload", sa.JSON(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("ix_outbox_messages_unpublished_id", "outbox_messages", ["id"], unique=False, postgresql_where=sa.text("published_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_messages_unpublished_id", table_name="outbox_messages", postgresql_where=sa.text("published_at IS NULL"))
    op.drop_table("outbox_messages")
    # ### end Alembic commands ###
