"""empty message

Revision ID: 3276dc0922d8
Revises: 4857f5df4dd6
Create Date: 2026-07-11 17:27:03.747222

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3276dc0922d8"
down_revision: Union[str, Sequence[str], None] = "4857f5df4dd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_outbox_messages_unpublished_id",
        "outbox_messages",
        ["id"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outbox_messages_unpublished_id",
        table_name="outbox_messages",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    # ### end Alembic commands ###
