services:
  library-backend:
    container_name: tempo.library.backend
    build:
      context: .
      target: backend
      network: host
    env_file:
      - .dev/.env.docker.local
    networks:
      - local-network
    ports:
      - 8004:8080

  library-consumer:
    container_name: tempo.library.consumer
    build:
      context: .
      target: consumer
      network: host
    env_file:
      - .dev/.env.docker.local

    networks:
      - local-network

networks:
  local-network:
    name: local.network
    external: true
