[project]
name = "toolkit"
version = "0.1.6"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dmitry", email = "zubashenkod@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pydantic (>=2.13.4,<3.0.0)",
    "boto3 (>=1.43.25,<2.0.0)",
    "boto3-stubs[essential] (>=1.43.25,<2.0.0)",
    "pyjwt[crypto] (>=2.13.0,<3.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "aiohttp (>=3.14.1,<4.0.0)",
    "faststream[rabbit] (>=0.7.1,<0.8.0)"
]

[[tool.uv.index]]
name = "pypiroska"
url = "http://localhost:1010/"
publish-url = "http://localhost:1010/"
explicit = true

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"
