"""alter uploads.created_by attribute str -> uuid.

Revision ID: 57beaf255aa8
Revises: e55e243927b3
Create Date: 2026-06-12 02:21:21.124449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57beaf255aa8'
down_revision: Union[str, Sequence[str], None] = 'e55e243927b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = 'e55e243927b3'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploads', 'created_by',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               postgresql_using='created_by::uuid',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploads', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
