[project]
name = "streaming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "uvicorn (>=0.49.0,<0.50.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "dishka (>=1.10.1,<2.0.0)",
    "pytest (>=9.1.0,<10.0.0)",
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "faker (>=40.23.0,<41.0.0)"
]

[tool.uv.sources]
tempo-toolkit-contracts = { path = "../toolkit/packages/contracts", editable = true }
tempo-toolkit-application = { path = "../toolkit/packages/application", editable = true }
tempo-toolkit-infrastructure = { path = "../toolkit/packages/infrastructure", editable = true }

[dependency-groups]
local = [
    "tempo-toolkit-contracts",
    "tempo-toolkit-application",
    "tempo-toolkit-infrastructure[web,keycloak,redis,s3]",
]

[tool.pytest.ini_options]
pythonpath = ["src", "."]
testpaths = ["tests"]
asyncio_mode = "auto"
